version: "3.8"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: ${DB_PASS}
        ports:
            - "1433:1433"
        volumes:
            - sql_data:/var/opt/mssql
            - ./db:/db
        entrypoint: ["/bin/sh", "/db/entrypoint.sh"]
        networks:
            - backend

    forex-admin:
        build: .
        container_name: admin
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
        depends_on:
            - mssql
        networks:
            - backend
        volumes:
            - ./src:/app/src

volumes:
    sql_data:

networks:
    backend:
        driver: bridge
