apiVersion: apps/v1
kind: Deployment
metadata:
    name: booking-service
    labels:
        app: booking-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: booking-service
    template:
        metadata:
            labels:
                app: booking-service
        spec:
            containers:
                - name: booking-service
                  image: homestay_management_wt_integration_booking_service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5000
                  env:
                      - name: DATABASE_URL
                        value: postgresql://booking_user:booking_pass@booking-db:5432/booking_db
                      - name: FLASK_ENV
                        value: development
                  volumeMounts:
                      - name: booking-service-volume
                        mountPath: /app
            volumes:
                - name: booking-service-volume
                  emptyDir: {}
            restartPolicy: Always
