# forex-admin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: forex-admin
    namespace: forex-crm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: forex-admin
    template:
        metadata:
            labels:
                app: forex-admin
        spec:
            containers:
                - name: forex-admin
                  image: froex-crm_forex-admin:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: DB_HOST
                        value: mssql
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: mssql-secret
                                key: DB_USER
                      - name: DB_PASS
                        valueFrom:
                            secretKeyRef:
                                name: mssql-secret
                                key: DB_PASS
                      - name: DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: mssql-secret
                                key: DB_NAME
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_SECRET
                  volumeMounts:
                      - name: admin-src
                        mountPath: /app/src
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "200m"
                      limits:
                          memory: "512Mi"
                          cpu: "400m"
            volumes:
                - name: admin-src
                  persistentVolumeClaim:
                      claimName: admin-src-pvc
