# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: forex-crm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: forex-crm_forex-client:latest
                  ports:
                      - containerPort: 3001
                  env:
                      - name: REACT_APP_API_URL
                        value: http://backend:4000
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
