apiVersion: v1
kind: Service
metadata:
    name: loyalty-service
    namespace: forex-crm
spec:
    selector:
        app: loyalty-service
    ports:
        - port: 8001
          targetPort: 8001
    type: ClusterIP

