# mssql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql
    namespace: forex-crm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
                - name: mssql
                  image: mcr.microsoft.com/mssql/server:2022-latest
                  ports:
                      - containerPort: 1433
                  env:
                      - name: ACCEPT_EULA
                        value: "Y"
                      - name: SA_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mssql-secret
                                key: SA_PASSWORD
                  volumeMounts:
                      - name: sql-data
                        mountPath: /var/opt/mssql
                      - name: db-scripts
                        mountPath: /db
                  resources:
                        requests:
                            memory: "256Mi"
                            cpu: "200m"
                        limits:
                            memory: "512Mi"
                            cpu: "400m"

            volumes:
                - name: sql-data
                  persistentVolumeClaim:
                      claimName: sql-data-pvc
                - name: db-scripts
                  configMap:
                      name: db-scripts
