apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-proxy-config
    namespace: forex-crm
data:
    default.conf: |
        server {
            listen 80;
            server_name api.forex-crm.local;

            location /api/wallet/ {
                proxy_pass https://9ed0-2406-7400-10a-85d5-80bf-6fb2-e3c3-fdf7.ngrok-free.app/api/wallet/;
                proxy_http_version 1.1;

                proxy_set_header Host 9ed0-2406-7400-10a-85d5-80bf-6fb2-e3c3-fdf7.ngrok-free.app;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /api/offers/
            {
                proxy_pass https://9ed0-2406-7400-10a-85d5-80bf-6fb2-e3c3-fdf7.ngrok-free.app/api/offers/;
                proxy_http_version 1.1;

                proxy_set_header Host 9ed0-2406-7400-10a-85d5-80bf-6fb2-e3c3-fdf7.ngrok-free.app;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
