apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: forex-crm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:14
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_DB
                  volumeMounts:
                      - name: postgres-data
                        mountPath: /var/lib/postgresql/data
                      - name: init-db-scripts
                        mountPath: /docker-entrypoint-initdb.d/postgres1-init.sql
                        subPath: postgres1-init.sql
                        readOnly: true
                      - name: init-db-scripts
                        mountPath: /docker-entrypoint-initdb.d/postgres-init.sql
                        subPath: postgres-init.sql
                        readOnly: true
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
                      limits:
                          memory: "1Gi"
                          cpu: "500m"
            volumes:
                - name: postgres-data
                  persistentVolumeClaim:
                      claimName: postgres-data-pvc
                - name: init-db-scripts
                  configMap:
                      name: postgres-initdb-scripts