apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-data-pvc
    namespace: forex-crm
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loyalty-code-pvc
    namespace: forex-crm
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi