apiVersion: v1
kind: Service
metadata:
    name: web
    namespace: forex-crm
spec:
    selector:
        app: web
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
          nodePort: 32003
    type: NodePort
